# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Holt < Formula
  desc "Reverse HTTP tunnels for services that can only dial out, with a hub CLI and web console"
  homepage "https://github.com/openotters/holt"
  version "0.43.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openotters/holt/releases/download/v0.43.0/holt_darwin_amd64.tar.gz"
      sha256 "092af6a03336bbc53166878cada22265fc86ad560a6dceef8c3c86f43dfbb7ae"

      define_method(:install) do
        bin.install "holt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openotters/holt/releases/download/v0.43.0/holt_darwin_arm64.tar.gz"
      sha256 "648030a1b38207f56198f3ce87024daea062d11472edffd0555a7d02ca370570"

      define_method(:install) do
        bin.install "holt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/holt/releases/download/v0.43.0/holt_linux_amd64.tar.gz"
      sha256 "a05b935a5dbe9cf44d4f5c8b08f772b0b2c593ee49dce96534f665ac061c36d6"
      define_method(:install) do
        bin.install "holt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/holt/releases/download/v0.43.0/holt_linux_arm64.tar.gz"
      sha256 "c133d28980755fea622684cbe535c0f4cdf6e47bfdfc392581cfc9ba0a92e07d"
      define_method(:install) do
        bin.install "holt"
      end
    end
  end

  def caveats
    <<~EOS
      🌀  Quick start:

        holt hub --ui                 # run a hub (web console on 127.0.0.1:7201)
        holt enroll web               # mint a join token for a peer
        holt expose localhost:3000 --token <paste>   # expose a local service

      Reach the peer through the hub:

        curl -H 'x-tunnel-peer: web' http://127.0.0.1:7202/

      Hub state (cert, JWT secret, blocklist) lives in ~/.holt
    EOS
  end

  test do
    assert_match "holt", shell_output("#{bin}/holt --version")
  end
end
