# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Holt < Formula
  desc "Reverse HTTP tunnel over a single gRPC stream, with a hub CLI and web console"
  homepage "https://github.com/openotters/holt"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openotters/holt/releases/download/v0.6.0/holt_darwin_amd64.tar.gz"
      sha256 "a3e216a0372c977d721860a6877efdb2ab488ebeff4926138fa2382e955f2061"

      define_method(:install) do
        bin.install "holt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openotters/holt/releases/download/v0.6.0/holt_darwin_arm64.tar.gz"
      sha256 "c70ed0fa347d29a9c22350fe4246658cfdc6d8be9076f866bdd640dd23d794a1"

      define_method(:install) do
        bin.install "holt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/holt/releases/download/v0.6.0/holt_linux_amd64.tar.gz"
      sha256 "90e568d6824f968e576b7680f539bc607f52552b4a30d6ded99020ac4a7116dc"
      define_method(:install) do
        bin.install "holt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/holt/releases/download/v0.6.0/holt_linux_arm64.tar.gz"
      sha256 "7ac1f190c7251273b655d8ada518a770e2b8b1a34a66a336e79ad2903b1fb808"
      define_method(:install) do
        bin.install "holt"
      end
    end
  end

  def caveats
    <<~EOS
      🌀  Quick start:

        holt hub --ui                 # run a hub (web console on 127.0.0.1:7001)
        holt enroll web               # mint a join token for a peer
        holt expose localhost:3000 --token <paste>   # expose a local service

      Reach the peer through the hub:

        curl -H 'x-tunnel-peer: web' http://127.0.0.1:7002/

      Hub state (cert, JWT secret, blocklist) lives in ~/.holt
    EOS
  end

  test do
    assert_match "holt", shell_output("#{bin}/holt --version")
  end
end
