# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Holt < Formula
  desc "Reverse HTTP tunnel over a single gRPC stream, with a hub CLI and web console"
  homepage "https://github.com/openotters/holt"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openotters/holt/releases/download/v0.10.0/holt_darwin_amd64.tar.gz"
      sha256 "5e437cc19a728b106da7d2db9f21d5c15ca67610f953765b388565b4fe49fe33"

      define_method(:install) do
        bin.install "holt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openotters/holt/releases/download/v0.10.0/holt_darwin_arm64.tar.gz"
      sha256 "301cc409c92e86f78bcaaefb0b8e332259b42b415483309404cd5f191761bf41"

      define_method(:install) do
        bin.install "holt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/holt/releases/download/v0.10.0/holt_linux_amd64.tar.gz"
      sha256 "307842d554c82050162328d4840b4a5f9e9d74c746cd546455136a289aa640f2"
      define_method(:install) do
        bin.install "holt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/holt/releases/download/v0.10.0/holt_linux_arm64.tar.gz"
      sha256 "722f29d2a88124adb0119a91e68af2bf05992f5c03994b32fabc5f4f117df4a9"
      define_method(:install) do
        bin.install "holt"
      end
    end
  end

  def caveats
    <<~EOS
      🌀  Quick start:

        holt hub --ui                 # run a hub (web console on 127.0.0.1:7001)
        holt enroll web               # mint a join token for a peer
        holt expose localhost:3000 --token <paste>   # expose a local service

      Reach the peer through the hub:

        curl -H 'x-tunnel-peer: web' http://127.0.0.1:7002/

      Hub state (cert, JWT secret, blocklist) lives in ~/.holt
    EOS
  end

  test do
    assert_match "holt", shell_output("#{bin}/holt --version")
  end
end
