# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otters < Formula
  desc "Build, run, and chat with AI agents"
  homepage "https://github.com/openotters/openotters"
  version "1.0.0-alpha.126"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.126/otters_darwin_amd64.tar.gz"
      sha256 "15f9bcb3e536defb9f7c66a165172ce90575bbfb9e0a8ec97bbb77b21dd7f3b2"

      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.126/otters_darwin_arm64.tar.gz"
      sha256 "e52bf4dfee0aff26512c358b36f643a15a5308b9fb66aad6f13370aaa1fbb21e"

      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.126/otters_linux_amd64.tar.gz"
      sha256 "df785fd676578a6c809e250dd62f5667139e491f51f86227cb07b972bbab4be6"
      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.126/otters_linux_arm64.tar.gz"
      sha256 "26424839df83a9efef542266e5ae5fc3164ef781e582a4f9cfca3f0c6b2e5940"
      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
  end

  def post_install
    # Homebrew's post_install runs in a sandbox that blocks
    # writes to user-home paths (notably ~/Library/LaunchAgents)
    # and BuildErrors on recursive `brew services` calls. That
    # rules out fresh-install auto-start AND interactive prompts
    # from here — the only reliable lifecycle hook we have is
    # `launchctl kickstart`, which talks to launchd directly
    # (no filesystem write needed) and works on the upgrade path
    # when the plist is already in place from a prior
    # `brew services start`.
    #
    # The fresh-install + first-provider flow lives in caveats
    # below as two clear commands.
    return unless OS.mac?
    require "etc"

    home = Pathname.new(Etc.getpwuid(Process.uid).dir)
    plist_path = home/"Library/LaunchAgents/homebrew.mxcl.#{name}.plist"
    return unless plist_path.exist?

    uid = Process.uid
    system "launchctl", "kickstart", "-k", "gui/#{uid}/homebrew.mxcl.#{name}"
  end

  def caveats
    <<~EOS
      🦦  After install:

        brew services start otters     # start the daemon (auto-restarts on upgrade)
        otters executor docker         # optional, recommended (alt: system)
        brew services restart otters   # only if you changed the executor above
        otters provider add            # configure your model provider

      Reset state any time:
        otters clean

      Default paths and endpoints:
        socket:        ~/.otters/otters.sock
        agent data:    ~/.otters/agents
        logs:          #{var}/log/ottersd.{log,err.log}
        web UI + API:  http://127.0.0.1:5500  (loopback by default)

      The daemon ships with an embedded web UI — open
      http://127.0.0.1:5500 once it's running.

      Manage the service:
        brew services restart otters
        brew services stop otters
        brew services list
    EOS
  end

  service do
    run [opt_bin/"ottersd", "serve"]
    keep_alive successful_exit: false, crashed: true
    log_path var/"log/ottersd.log"
    error_log_path var/"log/ottersd.err.log"
  end

  test do
    assert_match "otters", shell_output("#{bin}/otters --version")
  end
end
