# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otters < Formula
  desc "Build, run, and chat with AI agents"
  homepage "https://github.com/openotters/openotters"
  version "1.0.0-alpha.118"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.118/otters_darwin_amd64.tar.gz"
      sha256 "5237335f0499e30ddabe20c5d7da38cc900f43b5e988126ad396ff93205d380f"

      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.118/otters_darwin_arm64.tar.gz"
      sha256 "0f9c50f264c32b00f8a41d81f15025628d3e3dbdb3d8c3a763f71c39b6c5e7b8"

      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.118/otters_linux_amd64.tar.gz"
      sha256 "b04a61e1488a37485bf929385f02556baa5ab6667387ee8345d1a933901b2fa6"
      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.118/otters_linux_arm64.tar.gz"
      sha256 "89c7fb2aace60f6c2f7d9531d06ae893e493a3d3cfadc9e289ece1d5687aedc8"
      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
  end

  def post_install
    # Homebrew's post_install runs in a sandbox that blocks
    # writes to user-home paths (notably ~/Library/LaunchAgents)
    # and BuildErrors on recursive `brew services` calls. That
    # rules out fresh-install auto-start AND interactive prompts
    # from here — the only reliable lifecycle hook we have is
    # `launchctl kickstart`, which talks to launchd directly
    # (no filesystem write needed) and works on the upgrade path
    # when the plist is already in place from a prior
    # `brew services start`.
    #
    # The fresh-install + first-provider flow lives in caveats
    # below as two clear commands.
    return unless OS.mac?
    require "etc"

    home = Pathname.new(Etc.getpwuid(Process.uid).dir)
    plist_path = home/"Library/LaunchAgents/homebrew.mxcl.#{name}.plist"
    return unless plist_path.exist?

    uid = Process.uid
    system "launchctl", "kickstart", "-k", "gui/#{uid}/homebrew.mxcl.#{name}"
  end

  def caveats
    <<~EOS
      🦦  First-time setup:
        otters init     # interactive wizard: starts the daemon, picks an executor, adds a provider, spawns a starter agent, and drops you into chat — about 60 seconds end to end.

      Re-run `otters init` any time; it picks up where you left off.

      Default paths and endpoints:
        socket:        ~/.otters/otters.sock
        agent data:    ~/.otters/agents
        logs:          #{var}/log/ottersd.{log,err.log}
        web UI + API:  http://127.0.0.1:5500  (loopback by default)

      The daemon ships with an embedded web UI baked into the binary —
      no separate install. Open http://127.0.0.1:5500 in your browser.
      The Connect/gRPC API is reachable on the same listener under /api.

      Customise the listener (then `brew services restart otters`):
        ottersd serve --http-addr 127.0.0.1:8080   # change the port
        ottersd serve --no-ui                      # API only
        ottersd serve --no-http                    # CLI only (Unix socket)

      Non-loopback binds require --auth-token.

      Manage the service:
        brew services restart otters    # pick up a new binary or config
        brew services stop otters       # stop it
        brew services list              # check status

      If you skipped the provider-setup prompt:
        otters provider add

      Get started:
        otters --help
        otters run <Agentfile>
        open http://127.0.0.1:5500
    EOS
  end

  service do
    run [opt_bin/"ottersd", "serve"]
    keep_alive successful_exit: false, crashed: true
    log_path var/"log/ottersd.log"
    error_log_path var/"log/ottersd.err.log"
  end

  test do
    assert_match "otters", shell_output("#{bin}/otters --version")
  end
end
