# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otters < Formula
  desc "Build, run, and chat with AI agents"
  homepage "https://github.com/openotters/openotters"
  version "1.0.0-alpha.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.2/otters_darwin_amd64.tar.gz"
      sha256 "08aa4e8bdefef8e2f594ef7fd70c89a5905647e2fb4b29ceb8da4a98af0eea01"

      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.2/otters_darwin_arm64.tar.gz"
      sha256 "8c2fa925836f6ca8241fe3325fd4b445ab336197c7897e89a3a8a6940820760f"

      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.2/otters_linux_amd64.tar.gz"
      sha256 "21ac6440a12f39d07c7063ee557bdba31fe81c15b88349c41c749cccebb55b26"
      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openotters/openotters/releases/download/v1.0.0-alpha.2/otters_linux_arm64.tar.gz"
      sha256 "b4d3fab01839645ddef338bc454cee783bbdc86087da664bfc22801b117d6f40"
      define_method(:install) do
        bin.install "otters"
        bin.install "ottersd"
      end
    end
  end

  def caveats
    <<~EOS
      The otters daemon (ottersd) has been installed but is not running.

      To run it in the background (launchd on macOS, systemd --user on Linux):
        brew services start otters

      To run it in the foreground for debugging:
        ottersd serve

      Default paths:
        socket:      ~/.otters/otters.sock
        agent data:  ~/.otters/agents
        logs:        #{var}/log/ottersd.{log,err.log} (service mode only)

      Get started once the daemon is running:
        otters --help
        otters run <Agentfile>

      Stop the service:
        brew services stop otters
    EOS
  end

  service do
    run [opt_bin/"ottersd", "serve"]
    keep_alive successful_exit: false, crashed: true
    log_path var/"log/ottersd.log"
    error_log_path var/"log/ottersd.err.log"
  end

  test do
    assert_match "otters", shell_output("#{bin}/otters --version")
  end
end
